import { type MetadataRoute } from 'next'
 
export default function sitemap(): MetadataRoute.Sitemap {
  // This file is intentionally left empty to disable the default Next.js sitemap generation.
  // The sitemap is now generated by the route handler at /sitemap.xml/route.ts
  // to ensure correct formatting and headers.
  return []
}
